if (BUILD_SHARED_LIBS)
    set(SDL_STATIC OFF)
    set(SDL_SHARED ON)
else()
    set(SDL_STATIC ON)
    set(SDL_SHARED OFF)
endif()
set(SDL_TEST_LIBRARY      OFF)
set(SDL_DISABLE_INSTALL   ON)
set(SDL_DISABLE_UNINSTALL ON)
set(SDL_VULKAN   ON)
set(SDL_DIRECTX  OFF)
set(SDL_OPENGL   OFF)
set(SDL_OPENGLES OFF)

FetchContent_Declare(sdl3 GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git" GIT_TAG "5755bde3b85fe0e7c77354bda6b787dfb8f350d2")
FetchContent_MakeAvailable(sdl3)
target_include_directories(${PROJECT_NAME} SYSTEM PRIVATE "${sdl3_SOURCE_DIR}/include/")
if (BUILD_SHARED_LIBS)
    target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3-shared)
else()
    target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3-static)
endif()