set(SDL_SHARED OFF)
if (SDL_SHARED)
    set(SDL_STATIC OFF)
else()
    set(SDL_STATIC ON)
endif()
set(SDL_TEST_LIBRARY      OFF)
set(SDL_DISABLE_INSTALL   ON)
set(SDL_DISABLE_UNINSTALL ON)
set(SDL_VULKAN   ON)
set(SDL_DIRECTX  OFF)
set(SDL_OPENGL   OFF)
set(SDL_OPENGLES OFF)

FetchContent_Declare(sdl3 GIT_REPOSITORY "https://github.com/libsdl-org/SDL.git" GIT_TAG "0fe660374741b05ca551b93fccc17d475643c74d" GIT_SHALLOW OFF) # disabled shallow because of git tag hash usage
FetchContent_MakeAvailable(sdl3)
target_include_directories(${PROJECT_NAME} SYSTEM PRIVATE "${sdl3_SOURCE_DIR}/include/")
if (SDL_SHARED)
    target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3-shared)
    set_target_properties(SDL3-shared PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin/")
else()
    target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3-static)
endif()