set(SPIRV_REFLECT_EXECUTABLE     OFF)
set(SPIRV_REFLECT_STATIC_LIB     ON)
set(SPIRV_REFLECT_BUILD_TESTS    OFF)
set(SPIRV_REFLECT_ENABLE_ASSERTS OFF)
set(SPIRV_REFLECT_ENABLE_ASAN    OFF)
FetchContent_Declare(spirv_reflect GIT_REPOSITORY "https://github.com/KhronosGroup/SPIRV-Reflect.git" GIT_TAG "vulkan-sdk-1.3.290.0" GIT_SHALLOW ON GIT_SUBMODULES "")
FetchContent_MakeAvailable(spirv_reflect)
target_link_libraries(${PROJECT_NAME} PRIVATE spirv-reflect-static)

set(SPIRV_BUILD_FUZZER OFF)
set(SPIRV_COLOR_TERMINAL OFF)
set(SPIRV_SKIP_TESTS ON)
set(SPIRV_SKIP_EXECUTABLES ON)
set(SKIP_SPIRV_TOOLS_INSTALL ON)
set(SPIRV_USE_SANITIZER OFF)
set(SPIRV_WARN_EVERYTHING OFF)
set(SPIRV_WERROR OFF)
set(SPIRV_CHECK_CONTEXT OFF)
set(SPIRV_TOOLS_BUILD_STATIC ON)
FetchContent_Declare(SPIRV-Headers GIT_REPOSITORY "https://github.com/KhronosGroup/SPIRV-Headers.git" GIT_TAG "vulkan-sdk-1.3.290.0" GIT_SHALLOW ON)
FetchContent_Declare(spirv_tools GIT_REPOSITORY "https://github.com/KhronosGroup/SPIRV-Tools.git" GIT_TAG "vulkan-sdk-1.3.290.0" GIT_SHALLOW ON GIT_SUBMODULES "")
FetchContent_MakeAvailable(SPIRV-Headers spirv_tools)

set(ENABLE_OPT ON)
set(ENABLE_HLSL OFF)
set(ENABLE_GLSLANG_JS OFF)
set(ENABLE_GLSLANG_BINARIES OFF)
set(BUILD_SHARED_LIBS OFF)
set(BUILD_EXTERNAL OFF)
set(GLSLANG_TESTS OFF)
set(GLSLANG_ENABLE_INSTALL OFF)
FetchContent_Declare(glslang GIT_REPOSITORY "https://github.com/KhronosGroup/glslang.git" GIT_TAG "vulkan-sdk-1.3.290.0" GIT_SHALLOW ON)
FetchContent_MakeAvailable(glslang)
target_link_libraries(${PROJECT_NAME} PRIVATE glslang::glslang)
target_include_directories(${PROJECT_NAME} SYSTEM PRIVATE "${glslang_SOURCE_DIR}/glslang/Public")